version: '3.8'

services:
    php-fpm:
        build:
            context: ./php-fpm
            args:
                username: ${USER_NAME}
                useruid: ${USER_UID}
        container_name: php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        networks:
            - kafka_network

    webserver:
        image: nginx:1.26.0
        container_name: web-server
        restart: unless-stopped
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        volumes:
            - ../:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
        networks:
            - kafka_network

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        volumes:
            - zookeeper_data:/data
        networks:
            - kafka_network

    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 3000
            KAFKA_MIN_INSYNC_REPLICAS: 1
            KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
        volumes:
            - kafka1_data:/kafka
        depends_on:
            - zookeeper
        networks:
            - kafka_network

    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        ports:
            - "9093:9093"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
            KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 3000
            KAFKA_MIN_INSYNC_REPLICAS: 1
            KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
        volumes:
            - kafka2_data:/kafka
        depends_on:
            - zookeeper
        networks:
            - kafka_network

volumes:
    kafka1_data:
    kafka2_data:
    zookeeper_data:

networks:
    kafka_network:
        driver: bridge
