version: '3.8'

services:
    php-fpm:
        build:
            context: ./php-fpm
            args:
                username: ${USER_NAME}
                useruid: ${USER_UID}
        container_name: php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        networks:
            - kafka_network

    webserver:
        image: nginx:1.26.0
        container_name: web-server
        restart: unless-stopped
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        volumes:
            - ../:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
        networks:
            - kafka_network

    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
            - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
        volumes:
            - kafka_data:/bitnami/kafka
        networks:
            - kafka_network

volumes:
    kafka_data:

networks:
    kafka_network:
        driver: bridge
